version: "3.8"
services:
  springboot-app:
    image: spring-sql
    restart: always
    build: .
    ports:
      - 8081:8080
    depends_on:
      - mysqldb

  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
